# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Xioustic
tagline:          Homepage and Blog for Xioustic Computer Services
description:      ""
url:              https://xioustic.com/
baseurl:          /

author:
  name:           'Xioustic'
  url:            https://xioustic.com/

paginate:         5
paginate_path:    "page:num"

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/xioustic/xioustic.github.io

gems:             [jekyll-paginate,jekyll-gist]
